pipeline {
    agent any
    parameters{
      choice(name: 'BUILD_RONDB_VERSION', choices: ['21.04', '22.10'], description: 'RonDB version to build. This is branch in SCM')
    }
    stages {
        stage("build") {
            steps {
              echo "Testing"  
            }
        }
        stage("test") {
            steps {
              echo "Testing"  
            }
        }
        stage("deploy") {
            steps {
              echo "deploying"  
            }
        }
    }   
}

